package main

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type sourceFile struct {
	Path     string
	SHA256   string
	Contents string
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "bpfgen: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	var outPath string
	var packageName string

	flags := flag.NewFlagSet("bpfgen", flag.ContinueOnError)
	flags.SetOutput(os.Stderr)
	flags.StringVar(&outPath, "out", "", "path to write the generated Go binding")
	flags.StringVar(&packageName, "package", "generated", "Go package name for the generated binding")
	if err := flags.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return err
	}

	if outPath == "" {
		return fmt.Errorf("-out is required")
	}
	if packageName == "" {
		return fmt.Errorf("-package is required")
	}

	inputs := flags.Args()
	if len(inputs) == 0 {
		return fmt.Errorf("at least one BPF source or header file is required")
	}
	outputInfo, outputStatErr := os.Stat(outPath)
	if outputStatErr != nil && !errors.Is(outputStatErr, os.ErrNotExist) {
		return fmt.Errorf("stat output %s: %w", outPath, outputStatErr)
	}

	sources := make([]sourceFile, 0, len(inputs))
	for _, input := range inputs {
		if outputStatErr == nil {
			inputInfo, err := os.Stat(input)
			if err != nil {
				return fmt.Errorf("stat input %s: %w", input, err)
			}
			if os.SameFile(outputInfo, inputInfo) {
				return fmt.Errorf("output %s must not overwrite input %s", outPath, input)
			}
		}

		contents, err := os.ReadFile(input)
		if err != nil {
			return fmt.Errorf("read %s: %w", input, err)
		}

		hash := sha256.Sum256(contents)
		sources = append(sources, sourceFile{
			Path:     filepath.ToSlash(filepath.Clean(input)),
			SHA256:   hex.EncodeToString(hash[:]),
			Contents: string(contents),
		})
	}

	output, err := render(packageName, sources)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := os.WriteFile(outPath, []byte(output), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	return nil
}

func render(packageName string, sources []sourceFile) (string, error) {
	if !token.IsIdentifier(packageName) || packageName == "_" {
		return "", fmt.Errorf("invalid Go package name %q", packageName)
	}

	var builder strings.Builder

	builder.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	builder.WriteString("package ")
	builder.WriteString(packageName)
	builder.WriteString("\n\n")
	builder.WriteString("type SourceFile struct {\n")
	builder.WriteString("\tPath string\n")
	builder.WriteString("\tSHA256 string\n")
	builder.WriteString("\tContents string\n")
	builder.WriteString("}\n\n")
	builder.WriteString("var Sources = []SourceFile{\n")

	for _, source := range sources {
		builder.WriteString("\t{\n")
		builder.WriteString("\t\tPath: ")
		builder.WriteString(strconv.Quote(source.Path))
		builder.WriteString(",\n")
		builder.WriteString("\t\tSHA256: ")
		builder.WriteString(strconv.Quote(source.SHA256))
		builder.WriteString(",\n")
		builder.WriteString("\t\tContents: ")
		builder.WriteString(strconv.Quote(source.Contents))
		builder.WriteString(",\n")
		builder.WriteString("\t},\n")
	}

	builder.WriteString("}\n\n")
	builder.WriteString("func SourceByPath(path string) (SourceFile, bool) {\n")
	builder.WriteString("\tfor _, source := range Sources {\n")
	builder.WriteString("\t\tif source.Path == path {\n")
	builder.WriteString("\t\t\treturn source, true\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn SourceFile{}, false\n")
	builder.WriteString("}\n")

	formatted, err := format.Source([]byte(builder.String()))
	if err != nil {
		return "", fmt.Errorf("format generated Go source: %w", err)
	}
	return string(formatted), nil
}
